name: DwarfForge
main: org.simiancage.bukkit.DwarfForge.DwarfForge
version: 2.8
author: Don Redhorse


permissions:
    dwarfforge.*:
        description: Gives access to all DwarfForge commands.
        children:
            dwarfforge.create: true
            dwarfforge.use: true
            dwarfforge.destroy: true
    dwarfforge.create:
        decription: Allows you to create a Dwarven forge.
        default: true
    dwarfforge.use:
        decription: Allows you to use a Dwarven forge.
        default: true
    dwarfforge.destroy:
        decription: Allows you to destroy a Dwarven forge.
        default: true

